### ISSUE TITLE
flutter pub get failed on cloning "auto_size_text" package

### ISSUE THREAD

**Issue by mdsadiqueinam** [gskinnerTeam/flutter-folio#76]
flutter pub get failed on cloning "auto_size_text" package because in "pubspec.yaml" the git url of 'auto_size_text' is "git://github.com/gskinnerTeam/auto_size_text.git" it should be either "https://github.com/gskinnerTeam/auto_size_text.git" or "git@github.com/gskinnerTeam/auto_size_text.git"

**Comment by rubiii** [comment]
I changed the GitHub target in `pubspec.yml` to `https://github.com/gskinnerTeam/auto_size_text.git` which fixed the issue for me.

**Comment by ahmed-adly-khalil** [comment]
thanks @rubiii that worked for me!

**Comment by erleizh** [comment]
![image](https://user-images.githubusercontent.com/15859155/191674936-b9b55ce4-90aa-4188-9f64-cfe4a3a11e97.png)
The named parameter 'textBuilder' isn't defined. 
Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'textBuilder'.

**Comment by erleizh** [comment]
``` yaml
  auto_size_text:
    git:
      url: git@github.com:gskinnerTeam/auto_size_text.git
      ref: feature-add-textbuilder
```
fixed textBuilder  isn't defined.
